#!/bin/bash

# https://github.com/drebrb/shebangs

User=$(whoami)

install() { 
    cp scripts/n* /usr/local/bin && echo "Installation complete!" || echo "Installation failed!"
}

if [ "$User" = "root" ]
then
    install
else
    echo "Run with sudo."
fi
